name: Swagger API Docs Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2

jobs:
  deploy:
    name: Deploy-Swagger
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: deploy sources to s3 bucket
      run: |
        aws s3 sync ./src ${{ secrets.S3_PATH }}